src/Entity/MemberGroup.php
<?php

namespace App\Entity;

use App\Repository\MemberGroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MemberGroupRepository::class)]
class MemberGroup
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_enrolment = null;

    #[ORM\Column(length: 255)]
    private ?string $role = null;

    #[ORM\ManyToMany(targetEntity: group::class, inversedBy: 'memberGroups')]
    private Collection $groupe;

    public function __construct()
    {
        $this->groupe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEnrolment(): ?\DateTimeInterface
    {
        return $this->date_enrolment;
    }

    public function setDateEnrolment(?\DateTimeInterface $date_enrolment): static
    {
        $this->date_enrolment = $date_enrolment;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    /**
     * @return Collection<int, group>
     */
    public function getGroupe(): Collection
    {
        return $this->groupe;
    }

    public function addGroupe(group $groupe): static
    {
        if (!$this->groupe->contains($groupe)) {
            $this->groupe->add($groupe);
        }

        return $this;
    }

    public function removeGroupe(group $groupe): static
    {
        $this->groupe->removeElement($groupe);

        return $this;
    }
}

src/Form/MemberGroupType.php
<?php

namespace App\Form;

use App\Entity\MemberGroup;
use App\Entity\group;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MemberGroupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_enrolment')
            ->add('role')
            ->add('groupe', EntityType::class, [
                'class' => group::class,
'choice_label' => 'id',
'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MemberGroup::class,
        ]);
    }
}

src/Controller/MemberGroupController.php
<?php

namespace App\Controller;

use App\Entity\MemberGroup;
use App\Form\MemberGroupType;
use App\Repository\MemberGroupRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/member/group')]
class MemberGroupController extends AbstractController
{
    #[Route('/', name: 'app_member_group_index', methods: ['GET'])]
    public function index(MemberGroupRepository $memberGroupRepository): Response
    {
        return $this->render('member_group/index.html.twig', [
            'member_groups' => $memberGroupRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_member_group_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $memberGroup = new MemberGroup();
        $form = $this->createForm(MemberGroupType::class, $memberGroup);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($memberGroup);
            $entityManager->flush();

            return $this->redirectToRoute('app_member_group_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('member_group/new.html.twig', [
            'member_group' => $memberGroup,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_member_group_show', methods: ['GET'])]
    public function show(MemberGroup $memberGroup): Response
    {
        return $this->render('member_group/show.html.twig', [
            'member_group' => $memberGroup,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_member_group_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, MemberGroup $memberGroup, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MemberGroupType::class, $memberGroup);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_member_group_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('member_group/edit.html.twig', [
            'member_group' => $memberGroup,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_member_group_delete', methods: ['POST'])]
    public function delete(Request $request, MemberGroup $memberGroup, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$memberGroup->getId(), $request->request->get('_token'))) {
            $entityManager->remove($memberGroup);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_member_group_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/member_group/_delete_form.html.twig
<form method="post" action="{{ path('app_member_group_delete', {'id': member_group.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ member_group.id) }}">
    <button class="btn">Delete</button>
</form>

templates/member_group/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/member_group/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MemberGroup{% endblock %}

{% block body %}
    <h1>Edit MemberGroup</h1>

    {{ include('member_group/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_member_group_index') }}">back to list</a>

    {{ include('member_group/_delete_form.html.twig') }}
{% endblock %}

templates/member_group/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MemberGroup index{% endblock %}

{% block body %}
    <h1>MemberGroup index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_enrolment</th>
                <th>Role</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for member_group in member_groups %}
            <tr>
                <td>{{ member_group.id }}</td>
                <td>{{ member_group.dateEnrolment ? member_group.dateEnrolment|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ member_group.role }}</td>
                <td>
                    <a href="{{ path('app_member_group_show', {'id': member_group.id}) }}">show</a>
                    <a href="{{ path('app_member_group_edit', {'id': member_group.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_member_group_new') }}">Create new</a>
{% endblock %}

templates/member_group/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New MemberGroup{% endblock %}

{% block body %}
    <h1>Create new MemberGroup</h1>

    {{ include('member_group/_form.html.twig') }}

    <a href="{{ path('app_member_group_index') }}">back to list</a>
{% endblock %}

templates/member_group/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MemberGroup{% endblock %}

{% block body %}
    <h1>MemberGroup</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ member_group.id }}</td>
            </tr>
            <tr>
                <th>Date_enrolment</th>
                <td>{{ member_group.dateEnrolment ? member_group.dateEnrolment|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ member_group.role }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_member_group_index') }}">back to list</a>

    <a href="{{ path('app_member_group_edit', {'id': member_group.id}) }}">edit</a>

    {{ include('member_group/_delete_form.html.twig') }}
{% endblock %}